// <auto-generated />
using System;
using FormularioDinamico.Modulos.Formularios.Infraestrutura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FormularioDinamico.Modulos.Formularios.Infraestrutura.Persistencia.Migrations
{
    [DbContext(typeof(ContextoFormulariosDb))]
    [Migration("20260413230000_AdicionarCampoAtivo")]
    partial class AdicionarCampoAtivo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FormularioDinamico.Modulos.Formularios.Dominio.Formulario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Arquivado")
                        .HasColumnType("boolean");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid?>("VersaoPublicadaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AtualizadoEm");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.ToTable("formularios", (string)null);
                });

            modelBuilder.Entity("FormularioDinamico.Modulos.Formularios.Dominio.RegistroAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetalhesJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("EntidadeId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("Modulo", "Acao");

                    b.ToTable("logs_auditoria", (string)null);
                });

            modelBuilder.Entity("FormularioDinamico.Modulos.Formularios.Dominio.SubmissaoFormulario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("DadosRespostaJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("FormularioId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadadosJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VersaoFormularioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("FormularioId");

                    b.HasIndex("VersaoFormularioId");

                    b.ToTable("submissoes_formulario", (string)null);
                });

            modelBuilder.Entity("FormularioDinamico.Modulos.Formularios.Dominio.TipoCampoCatalogo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<bool>("AceitaMascara")
                        .HasColumnType("boolean");

                    b.Property<bool>("AceitaOpcoes")
                        .HasColumnType("boolean");

                    b.Property<bool>("AceitaValidacoes")
                        .HasColumnType("boolean");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.ToTable("catalogo_tipos_campo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "texto-curto",
                            AceitaMascara = true,
                            AceitaOpcoes = false,
                            AceitaValidacoes = true,
                            Descricao = "Entrada textual de linha única.",
                            Nome = "Texto curto"
                        },
                        new
                        {
                            Id = "texto-longo",
                            AceitaMascara = false,
                            AceitaOpcoes = false,
                            AceitaValidacoes = true,
                            Descricao = "Entrada textual multilinha.",
                            Nome = "Texto longo"
                        },
                        new
                        {
                            Id = "numero",
                            AceitaMascara = false,
                            AceitaOpcoes = false,
                            AceitaValidacoes = true,
                            Descricao = "Entrada numérica com limites opcionais.",
                            Nome = "Número"
                        },
                        new
                        {
                            Id = "email",
                            AceitaMascara = false,
                            AceitaOpcoes = false,
                            AceitaValidacoes = true,
                            Descricao = "Entrada textual com formato de e-mail.",
                            Nome = "E-mail"
                        },
                        new
                        {
                            Id = "data",
                            AceitaMascara = false,
                            AceitaOpcoes = false,
                            AceitaValidacoes = true,
                            Descricao = "Campo de data.",
                            Nome = "Data"
                        },
                        new
                        {
                            Id = "selecao",
                            AceitaMascara = false,
                            AceitaOpcoes = true,
                            AceitaValidacoes = true,
                            Descricao = "Lista suspensa com opções.",
                            Nome = "Seleção"
                        },
                        new
                        {
                            Id = "radio",
                            AceitaMascara = false,
                            AceitaOpcoes = true,
                            AceitaValidacoes = true,
                            Descricao = "Escolha única com botões de rádio.",
                            Nome = "Opção única"
                        },
                        new
                        {
                            Id = "caixa-marcacao",
                            AceitaMascara = false,
                            AceitaOpcoes = false,
                            AceitaValidacoes = false,
                            Descricao = "Controle booleano de marcação.",
                            Nome = "Caixa de marcação"
                        });
                });

            modelBuilder.Entity("FormularioDinamico.Modulos.Formularios.Dominio.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EhAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("FormularioDinamico.Modulos.Formularios.Dominio.VersaoFormulario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("FormularioId")
                        .HasColumnType("uuid");

                    b.Property<int>("NumeroVersao")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PublicadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublicadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("SchemaJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("StatusPublicacao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StatusPublicacao");

                    b.HasIndex("FormularioId", "NumeroVersao")
                        .IsUnique();

                    b.ToTable("formulario_versoes", (string)null);
                });

            modelBuilder.Entity("FormularioDinamico.Modulos.Formularios.Dominio.VersaoFormulario", b =>
                {
                    b.HasOne("FormularioDinamico.Modulos.Formularios.Dominio.Formulario", null)
                        .WithMany("Versoes")
                        .HasForeignKey("FormularioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormularioDinamico.Modulos.Formularios.Dominio.Formulario", b =>
                {
                    b.Navigation("Versoes");
                });
#pragma warning restore 612, 618
        }
    }
}
