<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" Version="3.0.*" />
    <PackageReference Include="Mediator.SourceGenerator" Version="3.0.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\FormularioDinamico.BuildingBlocks\FormularioDinamico.BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\Modulos\Formularios\FormularioDinamico.Modulos.Formularios.Aplicacao\FormularioDinamico.Modulos.Formularios.Aplicacao.csproj" />
    <ProjectReference Include="..\..\Modulos\Formularios\FormularioDinamico.Modulos.Formularios.Infraestrutura\FormularioDinamico.Modulos.Formularios.Infraestrutura.csproj" />
  </ItemGroup>

</Project>
